-- ============================================================================
-- ASIL Project Database Schema
-- SQLite database for football match predictions and evaluation
-- ============================================================================

-- ============================================================================
-- TEAMS TABLE
-- ============================================================================
-- Lookup table for all teams in the dataset.
-- Provides a normalized reference for team names, avoiding string duplication
-- in the matches table and ensuring consistent team identification across
-- all seasons. Team names from football-data.co.uk are stored as-is.
-- ============================================================================
CREATE TABLE teams (
    team_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    team_name   TEXT NOT NULL UNIQUE
);

-- ============================================================================
-- MATCHES TABLE
-- ============================================================================
-- Core table storing historical match data imported from football-data.co.uk.
-- Contains match results, basic statistics, and bookmaker probability data.
--
-- Probability columns (b365_*, avg_*) are converted from decimal odds using:
--   probability = 1 / decimal_odds
-- These represent implied probabilities from betting markets, useful as
-- baseline predictions to compare against our models.
--
-- The 'result' column uses standard notation: H=Home Win, D=Draw, A=Away Win
-- ============================================================================
CREATE TABLE matches (
    match_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    date            TEXT NOT NULL,              -- ISO format: YYYY-MM-DD
    season          TEXT NOT NULL,              -- e.g., '2122', '2223', '2324'
    home_team       TEXT NOT NULL,              -- Team name as it appears in source
    away_team       TEXT NOT NULL,              -- Team name as it appears in source
    home_goals      INTEGER NOT NULL,           -- Full-time home goals (FTHG)
    away_goals      INTEGER NOT NULL,           -- Full-time away goals (FTAG)
    result          TEXT NOT NULL,              -- Match result: 'H', 'D', or 'A'
    home_shots      INTEGER,                    -- Total home shots (HS)
    away_shots      INTEGER,                    -- Total away shots (AS)
    home_corners    INTEGER,                    -- Home corners (HC)
    away_corners    INTEGER,                    -- Away corners (AC)
    b365_home_prob  REAL,                       -- Bet365 implied home win probability
    b365_draw_prob  REAL,                       -- Bet365 implied draw probability
    b365_away_prob  REAL,                       -- Bet365 implied away win probability
    avg_home_prob   REAL,                       -- Market average home win probability
    avg_draw_prob   REAL,                       -- Market average draw probability
    avg_away_prob   REAL,                       -- Market average away win probability

    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0 AND away_goals >= 0)
);

-- ============================================================================
-- PREDICTIONS TABLE
-- ============================================================================
-- Stores probability predictions for matches from different models.
-- Each prediction contains both baseline (statistical) and LLM-generated
-- probabilities, allowing direct comparison of approaches.
--
-- - baseline_*_prob: Probabilities from a traditional statistical model
--   (e.g., Poisson regression, ELO ratings, or historical averages)
-- - llm_*_prob: Probabilities generated by the LLM after analyzing
--   team form, injuries, context, and other qualitative factors
-- - rationale_text: The LLM's explanation for its probability adjustments,
--   useful for understanding model reasoning and debugging
--
-- Predictions are made BEFORE the match occurs; timestamp records when
-- the prediction was generated for audit purposes.
-- ============================================================================
CREATE TABLE predictions (
    prediction_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    match_id            INTEGER NOT NULL,
    timestamp           TEXT NOT NULL,          -- ISO format: YYYY-MM-DDTHH:MM:SS
    baseline_home_prob  REAL NOT NULL,          -- Statistical model P(home win)
    baseline_draw_prob  REAL NOT NULL,          -- Statistical model P(draw)
    baseline_away_prob  REAL NOT NULL,          -- Statistical model P(away win)
    llm_home_prob       REAL NOT NULL,          -- LLM-adjusted P(home win)
    llm_draw_prob       REAL NOT NULL,          -- LLM-adjusted P(draw)
    llm_away_prob       REAL NOT NULL,          -- LLM-adjusted P(away win)
    rationale_text      TEXT,                   -- LLM explanation for adjustments

    FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE,

    -- Probabilities should sum to approximately 1.0 (allowing small float error)
    CHECK (baseline_home_prob >= 0 AND baseline_home_prob <= 1),
    CHECK (baseline_draw_prob >= 0 AND baseline_draw_prob <= 1),
    CHECK (baseline_away_prob >= 0 AND baseline_away_prob <= 1),
    CHECK (llm_home_prob >= 0 AND llm_home_prob <= 1),
    CHECK (llm_draw_prob >= 0 AND llm_draw_prob <= 1),
    CHECK (llm_away_prob >= 0 AND llm_away_prob <= 1)
);

-- ============================================================================
-- EVALUATIONS TABLE
-- ============================================================================
-- Post-match evaluation of prediction accuracy.
-- Links predictions to actual outcomes and computes scoring metrics.
--
-- Brier Score: Measures probabilistic prediction accuracy.
--   Formula: (predicted_prob - actual_outcome)^2, summed across all outcomes
--   Range: 0 (perfect) to 2 (worst possible)
--   Lower is better; rewards both calibration and sharpness.
--
-- - baseline_correct / llm_correct: Boolean indicating if the highest
--   probability outcome matched the actual result (for simple accuracy)
-- - error_tags: Comma-separated tags categorizing prediction errors
--   (e.g., 'upset', 'overconfident', 'form_miss', 'injury_factor')
-- - critique_text: Post-hoc analysis of what the model got right/wrong,
--   useful for identifying systematic biases or improvement areas
-- ============================================================================
CREATE TABLE evaluations (
    evaluation_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    match_id            INTEGER NOT NULL,
    prediction_id       INTEGER NOT NULL,
    outcome             TEXT NOT NULL,          -- Actual result: 'H', 'D', or 'A'
    baseline_brier_score REAL NOT NULL,         -- Brier score for baseline model
    llm_brier_score     REAL NOT NULL,          -- Brier score for LLM model
    baseline_correct    INTEGER NOT NULL,       -- 1 if baseline predicted correctly, 0 otherwise
    llm_correct         INTEGER NOT NULL,       -- 1 if LLM predicted correctly, 0 otherwise
    error_tags          TEXT,                   -- Comma-separated error categories
    critique_text       TEXT,                   -- Analysis of prediction performance

    FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE,
    FOREIGN KEY (prediction_id) REFERENCES predictions(prediction_id) ON DELETE CASCADE,

    CHECK (outcome IN ('H', 'D', 'A')),
    CHECK (baseline_correct IN (0, 1)),
    CHECK (llm_correct IN (0, 1)),
    CHECK (baseline_brier_score >= 0 AND baseline_brier_score <= 2),
    CHECK (llm_brier_score >= 0 AND llm_brier_score <= 2)
);

-- ============================================================================
-- INDEXES
-- ============================================================================
-- Optimized for common query patterns:
-- - Filtering matches by date range (time series analysis)
-- - Looking up matches by team (home or away)
-- - Joining predictions/evaluations to matches
-- - Filtering by season for seasonal analysis
-- ============================================================================

-- Matches indexes
CREATE INDEX idx_matches_date ON matches(date);
CREATE INDEX idx_matches_season ON matches(season);
CREATE INDEX idx_matches_home_team ON matches(home_team);
CREATE INDEX idx_matches_away_team ON matches(away_team);

-- Predictions indexes
CREATE INDEX idx_predictions_match_id ON predictions(match_id);
CREATE INDEX idx_predictions_timestamp ON predictions(timestamp);

-- Evaluations indexes
CREATE INDEX idx_evaluations_match_id ON evaluations(match_id);
CREATE INDEX idx_evaluations_prediction_id ON evaluations(prediction_id);
